apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
    - configMapKeyRef:
        name: app-config
    
    # 단일 환경 변수로 삽입
    # env:
    # - name: APP_COLOR
    #   valueFrom:
    #     configMapKeyRef:
    #       name: app-config
    #       key: APP_COLOR

    # 전체 데이터를 볼륨의 파일로 삽입
    # volumes:
    # - name: config-volume
    #   configMap:
    #     name: app-config