apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
    - secretRef:
        name: my-secret

    # 단일 환경 변수로 삽입
    # env:
    # - name: DB_Password
    #   valueFrom:
    #     secretKeyRef:
    #       name: my-secret
    #       key: DB_Password

    # 볼륨으로 마운트
    # volumes:
    # - name: secret-volume
    #   secret:
    #     secretName: my-secret